In [1]:
# @title
!pip install s3fs
!pip install pyarrow
!pip install "dask[complete]"
!pip install memory-profiler

Requirement already satisfied: s3fs in /usr/local/lib/python3.12/dist-packages (2026.3.0)
Requirement already satisfied: aiobotocore<4.0.0,>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from s3fs) (3.3.0)
Requirement already satisfied: fsspec==2026.3.0 in /usr/local/lib/python3.12/dist-packages (from s3fs) (2026.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0 in /usr/local/lib/python3.12/dist-packages (from s3fs) (3.13.3)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (0.13.0)
Requirement already satisfied: botocore<1.42.71,>=1.42.62 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (1.42.70)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (2.9.0.post0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (1.1.0)
Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (6.7.1)
Requirement already satisfied: wrapt<3.0.0,>=1.10.10 in /usr/local/lib/python3.12/dist-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (2.1.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (1.8.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (1.23.0)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (4.15.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore<1.42.71,>=1.42.62->aiobotocore<4.0.0,>=2.19.0->s3fs) (2.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->aiobotocore<4.0.0,>=2.19.0->s3fs) (1.17.0)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.12/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (3.11)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)
Requirement already satisfied: dask[complete] in /usr/local/lib/python3.12/dist-packages (2026.1.2)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (2026.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (26.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (0.12.1)
Requirement already satisfied: pyarrow>=16.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (18.1.0)
Collecting lz4>=4.3.2 (from dask[complete])
  Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask[complete]) (1.0.0)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (2.0.2)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (2.2.2)
Collecting distributed<2026.1.3,>=2026.1.2 (from dask[complete])
  Downloading distributed-2026.1.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: bokeh>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (3.8.2)
Requirement already satisfied: jinja2>=2.10.3 in /usr/local/lib/python3.12/dist-packages (from dask[complete]) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1.0->dask[complete]) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1.0->dask[complete]) (2.18.0)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1.0->dask[complete]) (11.3.0)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1.0->dask[complete]) (6.5.1)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1.0->dask[complete]) (2025.11.0)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.3,>=2026.1.2->dask[complete]) (1.1.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.3,>=2026.1.2->dask[complete]) (5.9.5)
Collecting sortedcontainers>=2.0.5 (from distributed<2026.1.3,>=2026.1.2->dask[complete])
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting tblib!=3.2.0,!=3.2.1,>=1.6.0 (from distributed<2026.1.3,>=2026.1.2->dask[complete])
  Downloading tblib-3.2.2-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: urllib3>=1.26.5 in /usr/local/lib/python3.12/dist-packages (from distributed<2026.1.3,>=2026.1.2->dask[complete]) (2.5.0)
Collecting zict>=3.0.0 (from distributed<2026.1.3,>=2026.1.2->dask[complete])
  Downloading zict-3.0.0-py2.py3-none-any.whl.metadata (899 bytes)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.10.3->dask[complete]) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[complete]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[complete]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[complete]) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0->dask[complete]) (1.17.0)
Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 20.6 MB/s eta 0:00:00
Downloading distributed-2026.1.2-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 55.7 MB/s eta 0:00:00
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Downloading tblib-3.2.2-py3-none-any.whl (12 kB)
Downloading zict-3.0.0-py2.py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 3.7 MB/s eta 0:00:00
Installing collected packages: sortedcontainers, zict, tblib, lz4, distributed
Successfully installed distributed-2026.1.2 lz4-4.4.5 sortedcontainers-2.4.0 tblib-3.2.2 zict-3.0.0
Collecting memory-profiler
  Downloading memory_profiler-0.61.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from memory-profiler) (5.9.5)
Downloading memory_profiler-0.61.0-py3-none-any.whl (31 kB)
Installing collected packages: memory-profiler
Successfully installed memory-profiler-0.61.0

In [2]:
from datetime import datetime
import dask.dataframe as dd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor
import s3fs # Ensure s3fs is imported for S3 access
import dask.dataframe as dd # Import dask.dataframe
%load_ext memory_profiler

**Loading the Data into a Dask Dataframe**

In [3]:
import dask.dataframe as dd

base_s3_uri = "s3://data604-g4-final/Combined_Data/run-1774669705550-part-block-0-r-"
runs = [f"{i:05d}" for i in range(123)]

s3_urls = [f"{base_s3_uri}{r}-uncompressed.parquet" for r in runs]

df = dd.read_parquet(s3_urls, storage_options={"anon": True})

In [4]:
df.head()

,day_of_week,fl_date,op_unique_carrier,op_carrier_airline_id,op_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin_airport_seq_id,origin_city_market_id,...,origin_weather_code,origin_wind_speed_10m,origin_wind_gusts_10m,dest_temperature_2m,dest_precipitation,dest_rain,dest_snowfall,dest_weather_code,dest_wind_speed_10m,dest_wind_gusts_10m
0,2,6/18/2024 12:00:00 AM,9E,20363,9E,N921XJ,5232,10397,1039707,30397,...,3.0,25.849905,47.519997,32.95,0.0,0.0,0.0,3.0,21.897945,47.519997
1,2,6/18/2024 12:00:00 AM,9E,20363,9E,N935XJ,5072,12478,1247805,31703,...,1.0,20.833395,39.6,31.35,0.0,0.0,0.0,0.0,12.245294,30.960001
2,2,6/18/2024 12:00:00 AM,AA,19805,AA,N402AN,1138,11057,1105703,31057,...,3.0,6.5693827,12.24,17.45,0.0,0.0,0.0,0.0,5.495161,8.64
3,2,6/18/2024 12:00:00 AM,AA,19805,AA,N449AN,1147,14107,1410702,30466,...,0.0,10.446206,24.84,28.1,0.0,0.0,0.0,0.0,17.462784,35.28
4,2,6/18/2024 12:00:00 AM,B6,20409,B6,N3044J,285,12478,1247805,31703,...,1.0,20.833395,39.6,31.35,0.0,0.0,0.0,0.0,12.245294,30.960001

**Preparing the Data for Modelling**

In [5]:
# converting date column to datetime
df["fl_date"] = dd.to_datetime(df["fl_date"], format='%m/%d/%Y %I:%M:%S %p')

In [6]:
# creating a new month column
df["month"] = df["fl_date"].dt.month

In [7]:
# checks counts of cancelled versus not cancelled fligts
df.cancelled.value_counts().compute()

cancelled
0.00    837176
1.00     13046
Name: count, dtype: int64[pyarrow]

In [8]:
# dropping flights that were cancelled
# these flights do not have a value for arrival delay
df = df[df["cancelled"] != "1.00"]

In [9]:
# drops rows with arrival delay missing
df = df[df["arr_delay"] != ""]

In [10]:
# checking for empty strings in the data
blank_counts = (df == '').sum()
blank_counts.compute()

day_of_week                   0.0
fl_date                       0.0
op_unique_carrier             0.0
op_carrier_airline_id         0.0
op_carrier                    0.0
tail_num                      0.0
op_carrier_fl_num             0.0
origin_airport_id             0.0
origin_airport_seq_id         0.0
origin_city_market_id         0.0
origin                        0.0
origin_city_name              0.0
origin_state_abr              0.0
dest_airport_id               0.0
dest_airport_seq_id           0.0
dest_city_market_id           0.0
dest                          0.0
dest_city_name                0.0
dest_state_abr                0.0
crs_dep_time                  0.0
dep_time                      0.0
dep_delay                     0.0
crs_arr_time                  0.0
arr_time                      0.0
arr_delay                     0.0
cancelled                     0.0
cancellation_code        835084.0
diverted                      0.0
air_time                      0.0
distance                      0.0
carrier_delay            650248.0
weather_delay            650248.0
nas_delay                650248.0
security_delay           650248.0
late_aircraft_delay      650248.0
fl_date_key                   0.0
dep_hour_key                  0.0
arr_hour_key                  0.0
origin_temperature_2m         0.0
origin_precipitation          0.0
origin_rain                   0.0
origin_snowfall               0.0
origin_weather_code           0.0
origin_wind_speed_10m         0.0
origin_wind_gusts_10m         0.0
dest_temperature_2m           0.0
dest_precipitation            0.0
dest_rain                     0.0
dest_snowfall                 0.0
dest_weather_code             0.0
dest_wind_speed_10m           0.0
dest_wind_gusts_10m           0.0
month                         0.0
dtype: double[pyarrow]

In [11]:
# checking for missing values
df.isna().sum().compute()

day_of_week              0
fl_date                  0
op_unique_carrier        0
op_carrier_airline_id    0
op_carrier               0
tail_num                 0
op_carrier_fl_num        0
origin_airport_id        0
origin_airport_seq_id    0
origin_city_market_id    0
origin                   0
origin_city_name         0
origin_state_abr         0
dest_airport_id          0
dest_airport_seq_id      0
dest_city_market_id      0
dest                     0
dest_city_name           0
dest_state_abr           0
crs_dep_time             0
dep_time                 0
dep_delay                0
crs_arr_time             0
arr_time                 0
arr_delay                0
cancelled                0
cancellation_code        0
diverted                 0
air_time                 0
distance                 0
carrier_delay            0
weather_delay            0
nas_delay                0
security_delay           0
late_aircraft_delay      0
fl_date_key              0
dep_hour_key             0
arr_hour_key             0
origin_temperature_2m    0
origin_precipitation     0
origin_rain              0
origin_snowfall          0
origin_weather_code      0
origin_wind_speed_10m    0
origin_wind_gusts_10m    0
dest_temperature_2m      0
dest_precipitation       0
dest_rain                0
dest_snowfall            0
dest_weather_code        0
dest_wind_speed_10m      0
dest_wind_gusts_10m      0
month                    0
dtype: int64

In [14]:
# converts columns with numeric variables to numeric data type
columns_to_convert = ['crs_dep_time','dep_time', 'dep_delay', 'crs_arr_time', 'arr_time', 'arr_delay', 'air_time', 'distance', 'origin_temperature_2m', 'origin_precipitation', 'origin_rain', 'origin_snowfall', 'origin_wind_speed_10m', 'origin_wind_gusts_10m', 'dest_temperature_2m', 'dest_precipitation', 'dest_rain', 'dest_snowfall', 'dest_wind_speed_10m', 'dest_wind_gusts_10m']
for col in columns_to_convert:
    df[col] = dd.to_numeric(df[col], errors='coerce')

In [15]:
# converts columns with categorical variables to category data type
df[["day_of_week", 'op_carrier', 'origin', 'dest', 'origin_weather_code', 'dest_weather_code', 'month']] = df[["day_of_week", 'op_carrier', 'origin', 'dest', 'origin_weather_code', 'dest_weather_code', 'month']].astype("category")
df.dtypes

day_of_week                     category
fl_date                   datetime64[ns]
op_unique_carrier        string[pyarrow]
op_carrier_airline_id    string[pyarrow]
op_carrier                      category
tail_num                 string[pyarrow]
op_carrier_fl_num        string[pyarrow]
origin_airport_id        string[pyarrow]
origin_airport_seq_id    string[pyarrow]
origin_city_market_id    string[pyarrow]
origin                          category
origin_city_name         string[pyarrow]
origin_state_abr         string[pyarrow]
dest_airport_id          string[pyarrow]
dest_airport_seq_id      string[pyarrow]
dest_city_market_id      string[pyarrow]
dest                            category
dest_city_name           string[pyarrow]
dest_state_abr           string[pyarrow]
crs_dep_time                       Int64
dep_time                           Int64
dep_delay                          Int64
crs_arr_time                       Int64
arr_time                           Int64
arr_delay                          Int64
cancelled                string[pyarrow]
cancellation_code        string[pyarrow]
diverted                 string[pyarrow]
air_time                           Int64
distance                           Int64
carrier_delay            string[pyarrow]
weather_delay            string[pyarrow]
nas_delay                string[pyarrow]
security_delay           string[pyarrow]
late_aircraft_delay      string[pyarrow]
fl_date_key              string[pyarrow]
dep_hour_key             string[pyarrow]
arr_hour_key             string[pyarrow]
origin_temperature_2m              Int64
origin_precipitation               Int64
origin_rain                        Int64
origin_snowfall                    Int64
origin_weather_code             category
origin_wind_speed_10m              Int64
origin_wind_gusts_10m              Int64
dest_temperature_2m                Int64
dest_precipitation                 Int64
dest_rain                          Int64
dest_snowfall                      Int64
dest_weather_code               category
dest_wind_speed_10m                Int64
dest_wind_gusts_10m                Int64
month                           category
dtype: object

In [16]:
# drops columns that will not be used in the model
df = df.drop(columns = ["fl_date", "op_unique_carrier", "op_carrier_airline_id", "tail_num", "op_carrier_fl_num", "origin_airport_id", "origin_airport_seq_id", "origin_city_market_id", "origin_city_name", "origin_state_abr", "dest_airport_id", "dest_airport_seq_id", "dest_city_market_id", "dest_city_name", "dest_state_abr", "dep_time", "dep_delay", "arr_time", "cancelled", "cancellation_code", "diverted", "air_time", "carrier_delay", "weather_delay", "nas_delay", "security_delay", "late_aircraft_delay", "fl_date_key", "dep_hour_key", "arr_hour_key"])

In [17]:
# checks the type of data for the remaining columns
df.dtypes

day_of_week              category
op_carrier               category
origin                   category
dest                     category
crs_dep_time                Int64
crs_arr_time                Int64
arr_delay                   Int64
distance                    Int64
origin_temperature_2m       Int64
origin_precipitation        Int64
origin_rain                 Int64
origin_snowfall             Int64
origin_weather_code      category
origin_wind_speed_10m       Int64
origin_wind_gusts_10m       Int64
dest_temperature_2m         Int64
dest_precipitation          Int64
dest_rain                   Int64
dest_snowfall               Int64
dest_weather_code        category
dest_wind_speed_10m         Int64
dest_wind_gusts_10m         Int64
month                    category
dtype: object

In [18]:
# drops any remaing missing values
df = df.dropna()
# ensures there are no longer any missing values
df.isna().sum().compute()

day_of_week              0
op_carrier               0
origin                   0
dest                     0
crs_dep_time             0
crs_arr_time             0
arr_delay                0
distance                 0
origin_temperature_2m    0
origin_precipitation     0
origin_rain              0
origin_snowfall          0
origin_weather_code      0
origin_wind_speed_10m    0
origin_wind_gusts_10m    0
dest_temperature_2m      0
dest_precipitation       0
dest_rain                0
dest_snowfall            0
dest_weather_code        0
dest_wind_speed_10m      0
dest_wind_gusts_10m      0
month                    0
dtype: int64

**Model Training**

In [ ]:
# splits the dask dataframe into X (predictor variables) and y (the target variable)
y = df["arr_delay"]
X = df.drop(columns = "arr_delay")

In [ ]:
# splits the data into a train and test set
X_train, X_test, y_train, y_test = train_test_split(X.compute(), y.compute(), test_size = 0.2, random_state = 42)

In [ ]:
%%memit
# fits the train set to an XGBoost model
xg_model = XGBRegressor(enable_categorical = True)
xg_model.fit(X_train, y_train)

peak memory: 13561.09 MiB, increment: 2249.35 MiB

In [ ]:
xg_model.save_model("model.json")

Peak RAM usage with dask was calculated to be about 13.2 GB.

**Model Evaluation**

In [ ]:
# uses the trained model to make predictions on the test set
y_pred = xg_model.predict(X_test)
# evaluates the performance of the model on making predictions on the test set using mean absolute error
mae = mean_absolute_error(y_test, y_pred)
print(mae)

25.56243324279785